サインアップの実装
Sui1031/twcl-app pull request #1
Opened 2021-08-16 16:29 UTC by Sui1031

ジャンゴ最終課題1つ目の機能実装完了しました。

2021-08-17 02:51 UTC, Atiisann requested changes

2021-08-17 02:51 UTC, Atiisann commented on twcl/templates/twcl/base.html
> +</html>
EOF追加

-https://e-words.jp/w/EOF.html
- https://qiita.com/norikt/items/83674fadd79a88bf7824

2021-08-17 02:51 UTC, Atiisann commented on twcl/templates/twcl/home.html
> +finished
EOF追加

2021-08-17 02:51 UTC, Atiisann commented on twcl/templates/twcl/signup.html
> +      <!-- <h3>パスワード(確認用)</h3> -->
不要なら消してください！

2021-08-17 02:51 UTC, Atiisann commented on twcl/urls.py
> +]
EOF追加

2021-08-17 02:51 UTC, Atiisann commented on twcl/views.py
> +def signup(request):
画面描写に関わる関数は`○○_view`にしたほうが
後々、統一感がでるのと、一目で画面描写に関わる関数だとわかるのでおすすめです！

2021-08-17 02:51 UTC, Atiisann commented on twcl/views.py
> +from django.contrib.auth.forms import UserCreationForm
名前順の方がキレイなのと、あとで追加する時に順番に困らないです

import の順番について参考資料
- https://pep8-ja.readthedocs.io/ja/latest/#import

2021-08-17 02:51 UTC, Atiisann commented on twcl/views.py
> +    Form = UserCreationForm(request.POST)
変数名は小文字にしてください

- https://pep8-ja.readthedocs.io/ja/latest/#id36

2021-08-17 02:51 UTC, Atiisann commented on twcl/views.py
> +    Form = UserCreationForm()
変数名は小文字にしてください

- https://pep8-ja.readthedocs.io/ja/latest/#id36

2021-08-17 02:51 UTC, Atiisann commented on twcl/views.py
> +def showHome(request):
関数名に大文字は使いません
あと、`show_home_view`や`home_view`の方が個人的には好きです

- https://pep8-ja.readthedocs.io/ja/latest/#id36

2021-08-17 02:51 UTC, Atiisann commented on twproject/settings.py
> +# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
不要なら消してください！

2021-08-17 02:51 UTC, Atiisann commented on twproject/settings.py
> +]
EOF追加

2021-08-17 02:58 UTC, Atiisann commented
今後、動作確認したらスクショが欲しいです🙇‍♂️
一番上のコメントに載せておいてもらえると助かります！

2021-08-17 15:26 UTC, Sui1031 commented
夜遅くにすみません。
指摘していただいた箇所を修正しましたので確認お願いします。

2021-08-17 15:26 UTC, Sui1031 commented
質問なのですが、このようなメッセージはここではなくスラックで送った方がよろしいでしょうか。

2021-08-18 01:14 UTC, Atiisann commented
>質問なのですが、このようなメッセージはここではなくスラックで送った方がよろしいでしょうか。

ここにコメントして、スラックで「返信しましたー」的なのをメンションして送ってもらえらると気付きやすいので助かります🙇‍♂️

あと、コードの修正内容が反映されていないように見えるので
push したか確認してみてください！

2021-08-18 02:24 UTC, Sui1031 commented
申し訳ないです。反映させましたのでご確認お願いします！
スラックの件承知しました。

2021-08-18 02:38 UTC, Atiisann requested changes
わかりにくいレビューしてすいません！🙇‍♂️

残タスク
- あと２つのファイルにEOF追加
- import順を整理する
- htmlファイルのインデントの数を修正

2021-08-18 02:38 UTC, Atiisann commented on twcl/templates/twcl/base.html
> +</html>
ここ！！

2021-08-18 02:38 UTC, Atiisann commented on twcl/templates/twcl/home.html
> +finished
ここ！！

2021-08-18 02:38 UTC, Atiisann commented on twcl/views.py
> +from django.contrib.auth.forms import UserCreationForm
```python
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
```
こんな感じで、名前順（アルファベット順）に修正してください！
ここ、わかりにくいレビューしてごめんなさい🙇‍♂️

2021-08-18 02:38 UTC, Atiisann commented on twcl/templates/twcl/signup.html
> +                  {% endfor %}
レビュー漏れです🙇‍♂️
インデントが多いので修正お願いします

2021-08-20 14:00 UTC, Sui1031 commented
指摘していただいた3つの箇所修正しました。確認お願いします！

↓動作確認もしました。
![2021-08-20 (1)](https://user-images.githubusercontent.com/77341280/130244982-74813c31-71e8-434e-904e-cd8bf4c02dbd.png)

2021-08-20 23:56 UTC, Atiisann commented
LGTM!!

2021-08-23 08:54 UTC, fumiharun11 approved these changes
LGTM
![](https://media.giphy.com/media/WArtXMnYKuneg/giphy.gif)

2021-08-24 13:01 UTC, merged